// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1zUkfMl9jgmQfAwQX258mB3Kr22SeVrU',
    appId: '1:1003558852836:web:78f4ad69cb3629ad52f4f1',
    messagingSenderId: '1003558852836',
    projectId: 'san-pedro-app-a8610',
    authDomain: 'san-pedro-app-a8610.firebaseapp.com',
    storageBucket: 'san-pedro-app-a8610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirT5wd7szU1WZp6IH1TxCiA_iDA1YcsU',
    appId: '1:1003558852836:android:d9ad7f4ee296e97f52f4f1',
    messagingSenderId: '1003558852836',
    projectId: 'san-pedro-app-a8610',
    storageBucket: 'san-pedro-app-a8610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvA80qdUdf90f0jtoqPtA4bflK7EguKII',
    appId: '1:1003558852836:ios:89174c19874deb9d52f4f1',
    messagingSenderId: '1003558852836',
    projectId: 'san-pedro-app-a8610',
    storageBucket: 'san-pedro-app-a8610.appspot.com',
    iosBundleId: 'com.bmwaresd.spApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvA80qdUdf90f0jtoqPtA4bflK7EguKII',
    appId: '1:1003558852836:ios:f47fd548050a20fd52f4f1',
    messagingSenderId: '1003558852836',
    projectId: 'san-pedro-app-a8610',
    storageBucket: 'san-pedro-app-a8610.appspot.com',
    iosBundleId: 'com.bmwaresd.spApp.RunnerTests',
  );
}
